import { WidgetConfig } from './types';
declare class HotpotSwapWidget extends HTMLElement {
    private _shadowRoot;
    private config;
    private fromAmount;
    private toAmount;
    private fromTokenData;
    private toTokenData;
    private slippage;
    private showSettings;
    private showTokenSelector;
    private tokenSelectorMode;
    private tokenSearchQuery;
    private tokenFilterNetwork;
    private tokenList;
    private networksList;
    private isTokenListLoading;
    private swapStatusType;
    private swapStatusMessage;
    private isWalletConnectError;
    private swapTxHash;
    private intentIdForStatus;
    private intentStatusFromApi;
    private intentStatusPollTimer;
    private intentStatusPollStartedAt;
    private isSwapping;
    private walletManager;
    private walletState;
    private isLoadingQuote;
    private currentQuote;
    private quoteDebounceTimer;
    private tokenSearchDebounceTimer;
    private showDestinationAddress;
    private destinationAddress;
    private isWidgetVisible;
    private showConnectWalletModal;
    private isConnectingWallet;
    private isBalanceLoading;
    private displayFromTokenAsWrapped;
    private showDestinationAddressModal;
    constructor();
    connectedCallback(): Promise<void>;
    private getNetworkIconUrl;
    private renderTokenIcon;
    private initializeTokens;
    private ensureTokensMatchWallet;
    private fetchBalances;
    attributeChangedCallback(name: string, oldValue: string, newValue: string): void;
    static get observedAttributes(): string[];
    private parseAttributes;
    private render;
    private getWalletIconByType;
    private renderHeader;
    private formatBalance;
    private getSwapStatusFromQuote;
    private getEffectiveSwapStatus;
    private mapIntentStatusToSwapStatus;
    private isDarkTheme;
    private renderLoaderSvg;
    private renderLoader;
    private renderSwapDividerContent;
    private renderSwapStatusToast;
    private renderTransactionModal;
    private renderDestinationAddressModal;
    private formatUsd;
    private getDisplayFromSymbol;
    private renderSwapForm;
    private renderPriceImpactWarning;
    private renderSlippagePanel;
    private renderTokenSelector;
    private escapeHtml;
    private readonly WALLET_OPTIONS;
    private renderConnectWalletModal;
    private attachEventListeners;
    private getSwapButtonText;
    private openTokenSelector;
    private closeTokenSelector;
    private loadTokenList;
    private selectToken;
    private fetchQuoteDebounced;
    private fetchQuote;
    private handleSwap;
    private getErrorMessage;
    private showSwapStatusModal;
    private clearSwapStatus;
    private stopIntentStatusPolling;
    private readonly INTENT_STATUS_SUCCESS;
    private readonly INTENT_STATUS_FAILED;
    private startIntentStatusPolling;
    private getExplorerUrl;
}
export { HotpotSwapWidget };
export type { WidgetConfig };
//# sourceMappingURL=index.d.ts.map